---

- hosts: macos
  tasks:
  - name: update homebrew and upgrade all packages
    homebrew:
     update_homebrew: yes
     upgrade_all: yes
     name: dos2unix,git,htop,lftp,openvpn,unar,unrar,vim,wget,youtube-dl,p7zip
     state: present
